name = "vita3k-api"
main = "src/main.ts"
compatibility_date = "2023-10-02"

[triggers]
crons = ["*/5 * * * *"]

# github access token goes here
[vars]
# ACCESS_TOKEN = "github access token"


#[[d1_databases]]
# empty