name = "vita3k-api"
main = "src/main.ts"
compatibility_date = "2024-11-11"
upload_source_maps = true

[triggers]
crons = ["*/1 * * * *"]

# github access token goes here
[vars]
# ACCESS_TOKEN = "github access token"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "vita3k-api"
database_id = "2452c369-1d24-4bc9-9994-029c71619ca3"