name = "vita3k-api"
main = "src/main.ts"
compatibility_date = "2023-10-02"

[triggers]
crons = ["*/5 * * * *"]

# github access token goes here
[vars]
# ACCESS_TOKEN = "github access token"


[[d1_databases]]
binding = "DB"
database_name = "vita3k-api"
database_id = "2452c369-1d24-4bc9-9994-029c71619ca3"